import { LessonCategory } from "./lessons";

// Massively expanded lesson content
export const expandedCategories: LessonCategory[] = [
  {
    id: 'patterns',
    name: 'Checkmate Patterns',
    description: 'Master the 15 essential checkmate patterns',
    icon: '🎯',
    lessons: [
      {
        id: 'patterns-1',
        title: 'Back Rank Mate',
        description: 'Trap the king on the back rank. One of the most common checkmate patterns in chess.',
        difficulty: 'beginner',
        category: 'patterns',
        eloRequirement: 600,
        locked: false,
        estimatedTime: 15,
        objectives: [
          'Recognize back rank weakness',
          'Execute back rank mate with rook or queen',
          'Defend against back rank threats',
          'Create escape squares for your king',
        ],
        interactivePositions: [
          {
            fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
            question: 'White to move - deliver back rank mate',
            correctMove: 'Re8',
            explanation: 'Re8# is checkmate! The black king is trapped on the back rank.',
          },
        ],
        quiz: [
          {
            question: 'What is the main weakness in a back rank mate?',
            options: [
              'King has no escape squares',
              'King is in the center',
              'King has too many pieces',
              'King is too active',
            ],
            correctAnswer: 0,
            explanation: 'The king is trapped by its own pieces with no escape squares.',
          },
          {
            question: 'Best defense against back rank mate?',
            options: [
              'Attack opponent\'s king',
              'Create luft (escape square)',
              'Trade all pieces',
              'Push all pawns',
            ],
            correctAnswer: 1,
            explanation: 'Creating an escape square (luft) by moving a pawn prevents back rank mates.',
          },
        ],
      },
      {
        id: 'patterns-2',
        title: 'Smothered Mate',
        description: 'Deliver checkmate with a knight when the king is smothered by its own pieces.',
        difficulty: 'intermediate',
        category: 'patterns',
        eloRequirement: 1000,
        locked: false,
        estimatedTime: 20,
        objectives: [
          'Recognize smothered mate setup',
          'Use queen sacrifice to force position',
          'Deliver checkmate with knight',
          'Spot opportunities in your games',
        ],
        quiz: [
          {
            question: 'Which piece delivers the final blow in smothered mate?',
            options: ['Queen', 'Knight', 'Rook', 'Bishop'],
            correctAnswer: 1,
            explanation: 'The knight delivers checkmate while the king is trapped by its own pieces.',
          },
        ],
      },
      {
        id: 'patterns-3',
        title: 'Anastasia\'s Mate',
        description: 'Knight and rook coordinate to trap the king on the edge.',
        difficulty: 'intermediate',
        category: 'patterns',
        eloRequirement: 1200,
        locked: false,
        estimatedTime: 15,
      },
      {
        id: 'patterns-4',
        title: 'Arabian Mate',
        description: 'Rook and knight work together for elegant checkmate.',
        difficulty: 'intermediate',
        category: 'patterns',
        eloRequirement: 1200,
        locked: false,
        estimatedTime: 15,
      },
      {
        id: 'patterns-5',
        title: 'Greco\'s Mate',
        description: 'Bishop and rook/queen deliver mate on h7.',
        difficulty: 'intermediate',
        category: 'patterns',
        eloRequirement: 1400,
        locked: false,
        estimatedTime: 20,
      },
    ],
  },
  {
    id: 'famous-games',
    name: 'Famous Games',
    description: 'Learn from the greatest games ever played',
    icon: '⭐',
    lessons: [
      {
        id: 'famous-1',
        title: 'The Immortal Game',
        description: 'Anderssen vs Kieseritzky, 1851. A legendary king-side attack with multiple piece sacrifices.',
        difficulty: 'advanced',
        category: 'famous-games',
        eloRequirement: 1600,
        locked: false,
        estimatedTime: 30,
        videoUrl: 'https://youtube.com/watch?v=example',
        objectives: [
          'Understand sacrificial attacks',
          'Learn king-side attacking patterns',
          'Study piece coordination',
          'Recognize when to sacrifice material',
        ],
      },
      {
        id: 'famous-2',
        title: 'The Evergreen Game',
        description: 'Anderssen vs Dufresne, 1852. A masterpiece of combinational play.',
        difficulty: 'advanced',
        category: 'famous-games',
        eloRequirement: 1600,
        locked: false,
        estimatedTime: 30,
      },
      {
        id: 'famous-3',
        title: 'The Opera Game',
        description: 'Morphy vs Duke Karl and Count Isouard, 1858. Brilliant development and attack.',
        difficulty: 'intermediate',
        category: 'famous-games',
        eloRequirement: 1400,
        locked: false,
        estimatedTime: 25,
      },
    ],
  },
  {
    id: 'defense',
    name: 'Defensive Techniques',
    description: 'Learn to defend difficult positions',
    icon: '🛡️',
    lessons: [
      {
        id: 'defense-1',
        title: 'Defending Under Pressure',
        description: 'Techniques for holding worse positions and finding defensive resources.',
        difficulty: 'intermediate',
        category: 'defense',
        eloRequirement: 1400,
        locked: false,
        estimatedTime: 25,
        objectives: [
          'Stay calm under attack',
          'Find defensive moves',
          'Trade attacking pieces',
          'Create counterplay',
        ],
      },
      {
        id: 'defense-2',
        title: 'Prophylaxis',
        description: 'Stop opponent\'s plans before they execute them.',
        difficulty: 'advanced',
        category: 'defense',
        eloRequirement: 1800,
        locked: false,
        estimatedTime: 30,
      },
    ],
  },
  {
    id: 'positional',
    name: 'Positional Understanding',
    description: 'Master long-term strategic planning',
    icon: '🎨',
    lessons: [
      {
        id: 'positional-1',
        title: 'Weak Squares',
        description: 'Identify and exploit weak squares in opponent\'s position.',
        difficulty: 'advanced',
        category: 'positional',
        eloRequirement: 1600,
        locked: false,
        estimatedTime: 25,
      },
      {
        id: 'positional-2',
        title: 'The Minority Attack',
        description: 'Advanced pawn structure technique for creating weaknesses.',
        difficulty: 'expert',
        category: 'positional',
        eloRequirement: 2000,
        locked: false,
        estimatedTime: 30,
      },
    ],
  },
  {
    id: 'advanced-tactics',
    name: 'Advanced Tactics',
    description: 'Complex tactical combinations',
    icon: '⚡',
    lessons: [
      {
        id: 'advanced-tactics-1',
        title: 'Deflection',
        description: 'Force a piece away from defending a key square or piece.',
        difficulty: 'advanced',
        category: 'advanced-tactics',
        eloRequirement: 1600,
        locked: false,
        estimatedTime: 20,
      },
      {
        id: 'advanced-tactics-2',
        title: 'Decoy',
        description: 'Lure a piece to a fatal square.',
        difficulty: 'advanced',
        category: 'advanced-tactics',
        eloRequirement: 1600,
        locked: false,
        estimatedTime: 20,
      },
      {
        id: 'advanced-tactics-3',
        title: 'Zwischenzug (In-Between Move)',
        description: 'Insert a powerful intermediate move before the expected response.',
        difficulty: 'expert',
        category: 'advanced-tactics',
        eloRequirement: 1800,
        locked: false,
        estimatedTime: 25,
      },
    ],
  },
  {
    id: 'pawn-structures',
    name: 'Pawn Structures',
    description: 'Deep understanding of pawn formations',
    icon: '♟️',
    lessons: [
      {
        id: 'pawn-1',
        title: 'The Isolated Pawn',
        description: 'Understand strengths and weaknesses of isolated pawns.',
        difficulty: 'advanced',
        category: 'pawn-structures',
        eloRequirement: 1800,
        locked: false,
        estimatedTime: 30,
      },
      {
        id: 'pawn-2',
        title: 'Hanging Pawns',
        description: 'Two connected pawns on the 4th rank - dynamic or weak?',
        difficulty: 'expert',
        category: 'pawn-structures',
        eloRequirement: 2000,
        locked: false,
        estimatedTime: 30,
      },
    ],
  },
];

// Merge with existing categories
export function getAllCategories(): LessonCategory[] {
  // This will be imported alongside existing categories
  return expandedCategories;
}
